name: dmd
channels:
  - conda-forge
  - nvidia
  - photosynthesis-team
  - pytorch
dependencies:
  - python>=3.8, < 3.10  # package build failures on 3.10
  - click>=8.0
  - h5py
  - imageio
  - numpy>=1.20
  - pillow>=8.3.1
  - pip
  - piq
  - psutil
  - pytorch=1.12.1
  - requests
  - scipy>=1.7.1
  - tqdm
  - torchvision
  - pip:
    - black==22.3.0
    - deepdiff==6.7.1
    - flake8==3.9.2
    - fire
    - imageio-ffmpeg>=0.4.3
    - isort==5.9.2
    - neptune
    - notebook
    - pyspng
